// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyectoEF;

#nullable disable

namespace proyectoEF.Migrations
{
    [DbContext(typeof(TareasContext))]
    partial class TareasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("proyectoEF.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Peso")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("54210ee2-e34f-4a73-87ba-5be75a47c3b6"),
                            Cama = "20",
                            Name = "Activades pendientes"
                        },
                        new
                        {
                            CategoriaId = new Guid("54210ee2-e34f-4a73-87ba-5be75a47c3c4"),
                            Cama = "50",
                            Name = "Activades personales"
                        });
                });

            modelBuilder.Entity("proyectoEF.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriorityTask")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("54210ee2-e34f-4a73-87ba-5be75a47c310"),
                            CategoriaId = new Guid("54210ee2-e34f-4a73-87ba-5be75a47c3b6"),
                            CreatedDate = new DateTime(2024, 10, 4, 15, 19, 36, 278, DateTimeKind.Local).AddTicks(8922),
                            PriorityTask = 1,
                            Title = "pago de servivios pulico"
                        },
                        new
                        {
                            TareaId = new Guid("54210ee2-e34f-4a73-87ba-5be75a47c311"),
                            CategoriaId = new Guid("54210ee2-e34f-4a73-87ba-5be75a47c3c4"),
                            CreatedDate = new DateTime(2024, 10, 4, 15, 19, 36, 278, DateTimeKind.Local).AddTicks(8939),
                            PriorityTask = 0,
                            Title = "terminar de ver peliculas"
                        });
                });

            modelBuilder.Entity("proyectoEF.Models.Tarea", b =>
                {
                    b.HasOne("proyectoEF.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("proyectoEF.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
